CREATE TYPE GENDER AS ENUM('MALE', 'FEMALE');

CREATE TABLE PATIENTS (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    gender GENDER NOT NULL,
    birth_date TIMESTAMP NOT NULL,
    version SMALLINT NOT NULL
);
